# Generated by Django 4.1.3 on 2023-02-27 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_article_meta_description_article_meta_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ваше имя')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Ваш E-mail')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст вашего комментария')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активировано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
