# Generated by Django 4.1.3 on 2023-02-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Проверен'),
        ),
    ]
