# Generated by Django 4.1.3 on 2023-02-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название комментария'),
        ),
    ]
