# Generated by Django 4.1.3 on 2023-01-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_cart_meta_description_cart_meta_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='meta_title',
        ),
    ]
